stages:
  - deploy-prod
  - deploy-dev

.ssh_template: &ssh_config
  before_script:
    - apk update
    - apk add git
    # Setup SSH deploy keys
    - 'which ssh-agent || ( apk add openssh-client )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIV_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

.deploy:
  stage: deploy
  image: docker:latest
  tags:
    - shared
  variables:
    DOCKER_HOST: ""
  <<: *ssh_config
  script:
    - |
      ssh $SSH_USER@$SSH_HOST -p $SSH_PORT "cd ~/www/${CI_COMMIT_BRANCH} && \
      git reset HEAD --hard && \
      git checkout $CI_COMMIT_BRANCH && git pull origin $CI_COMMIT_BRANCH && \
      npm install && \
      npm run build && \
      exit"

deploy-production:
  extends: .deploy
  stage: deploy-prod
  dependencies: []
  environment:
    name: production
    url: https://cloudru.pairmax.digital
  only:
    - main

deploy-development:
  extends: .deploy
  stage: deploy-dev
  dependencies: []
  environment:
    name: development
    url: https://dev.cloudru.pairmax.digital
  only:
    - dev
